import type { Metadata } from "next";
import "./globals.css";
import { roboto_mono } from "@/app/layout";

export const metadata: Metadata = {
    title: "Men's clothes",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={roboto_mono.className}>
                {children}
            </body>
        </html>
    );
}
