import type { Metadata } from "next";
import Navbar from "@/components/mainPage/navbar";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/mainPage/footer";

export const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "E-commerce / Shop",
  description: "Generated by create next app for shop",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
  },
};

export default function ShopLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
+      <body className={`${roboto_mono.className} bg-white m-0`}>
+        {children}
+      </body>
+    </html>
  );
}